# -*- coding: utf-8 -*-
from . import service_product_suppliers
from . import acccount_move_line
from . import account_invoice
from . import factura_carga
from . import packing_list
from . import service_base
from . import asociados_al_servicio
from . import invoice_type
from . import service_type
from . import default_expenses
from . import res_partner
from . import vehiculo
from . import service_products
from . import service_carga
from . import tarifario
from . import fronteras
from . import depositos
from . import service_products_to_calendar
from . import catalogo_bultos
from . import codigo_contenedores
from . import hr_employee
from . import stock_picking
from . import bill_of_landing
from . import fleet_vehicle_cost
from . import comision_choferes
from . import action_type
from . import comision_vendedores
from . import liquidacion_proveedores
from . import account_tax
from . import setup_toools
from . import comision_choferes
from . import digest
